### ISSUE TITLE
Restarting postgresql can cause espolld to exit.

### ISSUE THREAD

**Issue by mitchell-es** [perfsonar/esmond#58]
If postgresql closes the connection espolld is using it can cause espolld to exit. The exception should probably be caught and the connection re-established rather than exiting. The end result is that applying a package update to postgresql can cause espolld to die and not restart.

**Comment by vvidic** [comment]
Do we work on this if espolld is not in the release?

**Comment by vvidic** [comment]
Please check if #75 fixes the issue.
