### ISSUE TITLE
Python 3 support in Esmond

### ISSUE THREAD

**Issue by arlake228** [perfsonar/esmond#88]
This was already done once, but need to verify it still holds.

**Comment by arlake228** [comment]
Still a fair amount to do here. Biggest issue here is that pycassa is not python 3 ready so need to replace with cassandra-driver.

**Comment by arlake228** [comment]
Decided to do this in 4.4 when we drop Cassandra since pycassa and thrift requirements are not python3 compatible and migrating would require changes to cassandra tables.

**Comment by tonin** [comment]
Ongoing work in [python3 branch](https://github.com/perfsonar/esmond/tree/python3).

**Comment by tonin** [comment]
Has been released in 4.3.0
