### ISSUE TITLE
The esmond RPM package should open port 80 and 443

### ISSUE THREAD

**Issue by tonin** [perfsonar/esmond#93]
A default esmond installation should automatically open ports 80 and 443 so that users don't need to do that themselves.  This is taken care of by the toolkit packages, but not when installing a central archive.

**Comment by arlake228** [comment]
See previous comment on maddish. I strongly disagree the Esmond package is the place to do this. I think what we want is the issue we created at the face-to-face here: https://github.com/perfsonar/toolkit/issues/382

**Comment by tonin** [comment]
Yes, right, forgot we already had this other issue opened.  Together with https://github.com/perfsonar/project/issues/1219 that will solve this.
