### ISSUE TITLE
[Doc] Obtaining API keys

### ISSUE THREAD

**Issue by candlerb** [perfsonar/esmond#94]
Just a minor suggestion.

At https://docs.perfsonar.net/esmond_api_rest.html#authentication-and-authorization it says that an api-key is required, but not where to get it from.

I made a guess, and found one using `select * from authtoken_token;` in the esmond database.  But if there's an official way to generate and/or invalidate API keys, I don't know what it is.

**Comment by arlake228** [comment]
See http://docs.perfsonar.net/multi_ma_install.html#authenticating-by-api-key. We should probably add some linkage between the docs.
